---
title: "My Englsih Activity Log : M.E.A.L"
author:
  - name: SIMON Louis
    url: 
date: 11-05-2019
output:
  distill::distill_article:
    self_contained: false
categories :
  - M.E.A.L
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

  From now on, you will use this article to include every single activity that you do in English in a chronological order (e.g. reading a book in English, watching TV shows and series in English, going to an English Evening in Mons, travelling to an English-speaking country, playing games in English such as the pretty exciting game LyricsTraining, etc.). You can even write a few lines about what you’ve watched/read/done and recommend certain things to your friends. The sky’s the limit! We value personal initiative and we will be happy to read whatever you have to offer.

# Tv series and movies
 
* Peaky Blinders (Serie)
* Black Mirror (Serie)
* The Dead Don't Die (Movie)
* Family Guy (Animated serie)
* Zoo (Serie)
* The End Of The F***ing World (serie)

# Podcasts and videos

* Podcasts by a videomakers band called Smosh (the podcasts are named Smoshcasts and are available on streamplatforms (like Apple Music and Spotify) or on Youtube )
* Various videos and sketches on Youtube from american or briton videomakers

# Videogames

* I have played videogames in english like "God of War" and "Red Dead Redemption" for exemple

# Applications 

* I have downloaded the "BBC News" application so that I can regulary check the news
* I have downloaded the "Word Reference" application which is a dictionnary
