---
title: "My english activity log"
---

From now on, you will use this article to include every single activity that you do in English in a chronological order (e.g. reading a book in English, watching TV shows and series in English, going to an English Evening in Mons, travelling to an English-speaking country, playing games in English such as the pretty exciting game LyricsTraining, etc.). You can even write a few lines about what you’ve watched/read/done and recommend certain things to your friends. The sky’s the limit! We value personal initiative and we will be happy to read whatever you have to offer.

# Tv series and movies
 
* Peaky Blinders (Serie)
* Black Mirror (Serie)
* The Dead Don't Die (Movie)
* Family Guy (Animated serie)
* Zoo (Serie)

# Podcasts and videos

* Smosh podcasts (from a videomaker band)
* Various videos and sketches on Youtube from american or briton videomakers

# Videogames

* Played videogames in english like "God of War" and "Red Dead Redemption" for exemple
